### PR TITLE
Fix #190: Isolate STATIC_CONFIG_OPTIONS

### LINKED ISSUE #190: WITH_THREAD should be kept per Context
Please see the sample code below.

============================== sample code ==============================
```java
import org.graalvm.polyglot.Context;

public class MultiContext1 {
    public static void main(String[] args) {
        try (Context ctx1 = Context.newBuilder("python").build();
             Context ctx2 = Context.newBuilder("python")
                .allowExperimentalOptions(true)
                .option("python.WithThread", "true").build()) {

            System.out.println("initialize start");
            ctx1.eval("python", "import _sysconfig");
            ctx2.eval("python", "import _sysconfig");
            System.out.println("initialize end");

            System.out.println("eval start");
            ctx1.eval("python", "print(_sysconfig.get_config_vars())");
            ctx2.eval("python", "print(_sysconfig.get_config_vars())");
            System.out.println("eval end");
        }
    }
}
```
============================== sample code ==============================

============================== output ==============================
```
initialize start
initialize end
eval start
{'WITH_THREAD': 1}
{'WITH_THREAD': 1}
eval end
```
============================== output ==============================

I think `WITH_THREAD` should be kept per Context, so the output should look like this.

============================== output ==============================
```
initialize start
initialize end
eval start
{'WITH_THREAD': 0}
{'WITH_THREAD': 1}
eval end
```
============================== output ==============================

### PR DESCRIPTION
**Pull request by kariya-mitsuru**
I think `WITH_THREAD` should be kept per Context.

### CODE REVIEW

**Comment by timfel** [comment]
Sorry, as mentioned on the issue, these options are simply going away in the next release

**Comment by msimacek** [comment]
Hi, the threading effort that will make this option obsolete is taking more time than expected and more people are running into the problem. I'd like to accept this PR to fix the problem until threading is complete.

**Comment by msimacek** [comment]
@timfel I noticed you said on the issue that it still wouldn't work very well when on the context. Do you think we could still accept this as an incremental improvement over the current situation to avoid other people tripping over this?

**Comment by timfel** [comment]
> @timfel I noticed you said on the issue that it still wouldn't work very well when on the context. Do you think we could still accept this as an incremental improvement over the current situation to avoid other people tripping over this?

yes, it's fine to accept as-is, we will refactor once the threading PR is ready

**Pull request merged**
